name: Miles Evan Rosenberg
favicon: null
layout_spectrum: 0.150884959846735
typography_spectrum: 0.3874341263435781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2359055131673813
  lightness: 0.39943523705005646
  saturation: 0.77557188924402
  rhythmicContrast: 0.42912748269736767
purpose: []
